# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0002_remove_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(related_name='comment', to='image_viewer.Comment'),
        ),
    ]
