# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0002_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
