# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0004_auto_20180609_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.CharField(choices=[('AFRICA', 'AFRICA'), ('EUROPE', 'EUROPE'), ('ASIA', 'ASIA'), ('NORTH_AMERICA', 'NORTH AMERICA'), ('SOUTH_AMERICA', 'SOUTH AMERICA'), ('AUSTRALIA', 'AUSTRALIA'), ('ANTARCTICA', 'ANTARCTICA')], default='AFRICA', max_length=30),
        ),
    ]
