# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0005_auto_20180609_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
