# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0007_location_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc',
            new_name='location_descrition',
        ),
    ]
